<a href="https://colab.research.google.com/github/rafaelaquinoo/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [6]:
import numpy as np
A = np.array([[1,1,1],[1,0,4],[0,0,5]])
B = np.array([[89],[89],[95]])
amt = np.linalg.inv(A).dot(B)
print(amt)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [7]:
A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
print(A)
B = np.array([[5],[15],[-20]])
print (B)

Apinv = np.linalg.pinv(A)

x = Apinv.dot(B)
print(x)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]
[[  5]
 [ 15]
 [-20]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3. Consider the matrix, (40 points)

1. Find the eigenvalue/s
2. Find the eigenvectors

In [3]:
import numpy as np
from scipy.linalg import solve
from numpy.linalg import eig

A = np.array([[8,5,-6],
             [-12,9,12],
             [-3,-3,5]])
w,v = np.linalg.eig(A)
print("The eigenvalues is/are:",w)
print("The eigenvectors are:",v)

The eigenvalues is/are: [10.+9.74679434j 10.-9.74679434j  2.+0.j        ]
The eigenvectors are: [[-6.19826768e-02-0.44653265j -6.19826768e-02+0.44653265j
   7.07106781e-01+0.j        ]
 [ 8.56977879e-01+0.j          8.56977879e-01-0.j
  -1.66861154e-16+0.j        ]
 [ 9.43214647e-03+0.24953295j  9.43214647e-03-0.24953295j
   7.07106781e-01+0.j        ]]
