<a href="https://colab.research.google.com/github/rafaelaquinoo/Linear-Algebra-58019/blob/main/Linear_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([[4,3],[5,9]]) #creation of matrix A
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[4 3]
 [5 9]]
[[ 0.42857143 -0.14285714]
 [-0.23809524  0.19047619]]


In [2]:
B = np.array([[20],[26]])
print(B)

[[20]
 [26]]


In [3]:
X = np.linalg.inv(A).dot(B)
print(X)

[[4.85714286]
 [0.19047619]]


In [5]:
X = np.dot(inv_A,B)
print(X)

[[4.85714286]
 [0.19047619]]


APPLICATION

In [7]:
A = np.array ([[20,10],[17,22]])
print(A)
Inv_A = np.linalg.inv(A)
print(Inv_A)

[[20 10]
 [17 22]]
[[ 0.08148148 -0.03703704]
 [-0.06296296  0.07407407]]


In [8]:
B = np.array([[350],[500]])
print(B)

[[350]
 [500]]


In [9]:
X = np.dot(Inv_A,B)
print(X)

[[10.]
 [15.]]


To check if the answer is correct

In [14]:
B = np.dot(A,X)
print(B)

[[350.]
 [500.]]


ACTIVITY

In [17]:
import numpy as np
A = np.array([[[4,3,2],[-2,2,3],[3,-5,2]]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[[ 4  3  2]
  [-2  2  3]
  [ 3 -5  2]]]
[[[ 0.15447154 -0.1300813   0.04065041]
  [ 0.10569106  0.01626016 -0.1300813 ]
  [ 0.03252033  0.23577236  0.11382114]]]


In [18]:
B = np.array([[[25],[-10],[-4]]])
print(B)

[[[ 25]
  [-10]
  [ -4]]]


In [20]:
X = np.linalg.inv(A).dot(B)
print(X)

[[[[ 5.]]

  [[ 3.]]

  [[-2.]]]]


In [21]:
x = np.dot(inv_A,B)
print(x)

[[[[ 5.]]

  [[ 3.]]

  [[-2.]]]]
