<a href="https://colab.research.google.com/github/rafaelaquinoo/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [1]:
import numpy as np #import Library
#the length and width of a square matrix are the same, it is a 5x5 matrix.
SquareMatrix = np.array ([[5,2,3,4,2],[2,4,5,3,6],[8,6,3,2,3],[4,0,0,0,0],[5,2,7,3,4]]) #5x5 matrix
print("This is an example of square matrix whose length is 5") #this section is optional
print() #this is for spacing purposes alone, and it is also optional.
print(SquareMatrix) #this is the final answer


This is an example of square matrix whose length is 5

[[5 2 3 4 2]
 [2 4 5 3 6]
 [8 6 3 2 3]
 [4 0 0 0 0]
 [5 2 7 3 4]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [2]:
import numpy as np
C = np.triu([[1,9,4,2,5],[6,2,5,3,8],[6,7,8,3,4]])
print(C)

[[1 9 4 2 5]
 [0 2 5 3 8]
 [0 0 8 3 4]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [3]:
#Create a symmetrical matrix
G = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(G)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [4]:
import numpy as np
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

invC = np.linalg.inv(C)

print("Inverse of Matrix C:")
print(invC)

Inverse of Matrix C:
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [5]:
C = np.array ([[1,2,3],
               [2,3,3],
               [3,4,-2]])

detOfC = np.linalg.det(C)

print("Determinant of the given matrix in Question 4:")
print(int(detOfC))

Determinant of the given matrix in Question 4:
5


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [6]:

eq = np.array([[5,4,1],
               [10,9,4],
               [10,13,15]])

const = np.array([[[3.4],
                   [8.8],
                   [19.2]]])

roots = np.linalg.inv(eq) @ const

print("Roots of the given linear equations:")
print(roots)

Roots of the given linear equations:
[[[0.2]
  [0.4]
  [0.8]]]
