<a href="https://colab.research.google.com/github/rafaelaquinoo/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([-2,-5])
print("Vector A is", A)
print("Vector B is", B)

Vector A is [4 3]
Vector B is [-2 -5]


In [2]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [3]:
U = np.array([[1,2,3],[4,5,6]])
U



array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
U = np.array([[1,2,3],[4,5,6]])
U.shape

(2, 3)

In [5]:
U = np.array([[1,2,3],[4,5,6]])
U.ndim

2

In [6]:
U = np.array([[1,2,3],[4,5,6]])
U.size

6

In [7]:
U = np.array([[1,2,3],[4,5,6]])
U
U.size

6

#Addition of Vector

In [8]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [9]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

#Subtraction of Vector

In [10]:
difference = addend1-addend2
difference

array([-1, -1,  0])

In [11]:
difference2 = np.subtract(addend1,addend2)
difference2

array([-1, -1,  0])

#Scaling

In [12]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

#Cross Product

In [13]:
A = np.array([2,3])
B = np.array([1,7])

cross = np.cross(A,B)
print(cross)

11


In [14]:
A = np.array([2,3,4])
B = np.array([1,7,1])

cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [ ]:
#Dot Product

In [15]:
import numpy as np
A = np.array ([2,3])
B = np.array ([1,7])

dot = np.dot(A,B)
print(dot)

23
